root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server.exe ./cmd/server"
  bin = "./tmp/server.exe"
  delay = 1000
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go"]
  kill_delay = "2s"
  rerun_delay = 500
  send_interrupt = true

[log]
  time = true

[misc]
  clean_on_exit = true
